# 1 - HTTP e HTTPS
quarkus.http.port=8081
quarkus.http.ssl-port=8444
quarkus.http.ssl.certificate.key-store-file=keystore.jks

# Config property allows for an external or internal
# location of Public Key to be specified.
mp.jwt.verify.publickey.location=publicKey.pem

# Config property allows for an external or internal location of Private
# Decryption Key to be specified.
mp.jwt.decrypt.key.location=privateKey.pem

# Expected value of the JWT iss (issuer) claim
mp.jwt.verify.issuer=https://localhost:8443
quarkus.http.ssl.certificate.key-store-file=keystore.jks
quarkus.http.ssl.certificate.key-store-password=password

%dev.quarkus.tls.trust-all=true

#MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=pw2
quarkus.datasource.password=pw2
quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.datasource.devservices.port=3306

# OpenTelemetry
quarkus.otel.service.name=users-service
quarkus.otel.exporter.otlp.traces.endpoint=http://localhost:4317
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n

# Graylog
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=localhost
quarkus.log.handler.gelf.port=12201


# Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
